name:                glask
version:             0.1.0.0
github:              "Taskkill/glask"
license:             BSD3
author:              "Taskkill"
maintainer:          "example@example.com"
copyright:           "2021 Taskkill"

extra-source-files:
- src/Compiler/Lexer/Lexer.x

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Taskkill/glask#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- utf8-string
- array
- directory
- filepath
- containers >= 0.6.2.1
- hspec
- transformers
- extra

library:
  source-dirs: src

executables:
  glask-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Weverything
    - -Wno-missing-safe-haskell-mode
    - -Wno-unsafe
    - -Wno-safe
    - -Wno-unused-packages
    dependencies:
    - glask

tests:
  glask-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glask
